[tool.poetry]
name = "tg-to-org"
version = "0.1.0"
description = ""
authors = ["harmitage <anthonyharmitage@pm.me>"]

[tool.poetry.dependencies]
python = "^3.8"
Pyrogram = "^2.0.30"
TgCrypto = "^1.2.3"
Flask = "^2.1.2"
jsonlines = "^3.0.0"
Flask-SQLAlchemy = "^2.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

